services:
  mailpit:
    image: axllent/mailpit
    container_name: mailpit_test
    ports:
      - "1025:1025"
      - "8025:8025"

  redis:
    image: redis
    container_name: redis_test
    ports:
      - "6379:6379"

  postgres:
    image: postgres
    container_name: postgres_test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flair_test
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d flair_test"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

  api:
    image: ghcr.io/flair-co/flair-api:latest
    container_name: api
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: test
      DB_HOST: postgres
      REDIS_URL: redis://redis:6379
      EMAIL_HOST: mailpit
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      mailpit:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
