services:
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog_test
    ports:
      - "1025:1025"
      - "8025:8025"

  redis:
    image: redis
    container_name: redis_test
    ports:
      - "6379:6379"

  postgres:
    image: postgres
    container_name: postgres_test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flair_test
    ports:
      - "5432:5432"

  api:
    image: ghcr.io/flair-co/flair-api:latest
    container_name: api
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: test
      DB_HOST: postgres
      REDIS_URL: redis://redis:6379
      EMAIL_HOST: mailhog
    depends_on:
      - mailhog
      - redis
      - postgres
