name: CI/CD

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-format:
    name: Lint & Format
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate routes
        run: npm run generate-routes

      - name: Run lint check
        run: npm run lint:check

      - name: Run format check
        run: npm run format:check

  build:
    name: Build
    runs-on: ubuntu-latest
    environment: test
    needs: [lint-format]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate routes
        run: npm run generate-routes

      - name: Build application
        run: npm run build

  e2e-test:
    name: E2E Tests
    timeout-minutes: 60
    runs-on: ubuntu-latest
    environment: test
    needs: [build]
    steps:
      - name: Checkout web repository
        uses: actions/checkout@v4

      - name: Start Docker E2E environment
        run: |
          cp docker-compose.e2e.yml docker-compose.yml
          docker compose -f docker-compose.yml up -d --build

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Install npm dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run E2E tests
        run: npm run test:e2e

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
