name: Web CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: development

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: 'npm'
      - run: npm ci
      - run: npm run generate-routes
      - run: npm run lint:check
      - run: npm run format:check
      - run: npm run build
