name: CI/CD

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-format:
    name: Lint & Format
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate routes
        run: npm run generate-routes

      - name: Run lint check
        run: npm run lint:check

      - name: Run format check
        run: npm run format:check

  build:
    name: Build
    runs-on: ubuntu-latest
    environment: development
    needs: [lint-format]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate routes
        run: npm run generate-routes

      - name: Build application
        run: npm run build

  e2e-test:
    name: E2E Tests
    runs-on: ubuntu-latest
    needs: [build, lint-format]
    steps:
      - name: Checkout web repository
        uses: actions/checkout@v4

      - name: Checkout API repository
        uses: actions/checkout@v4
        with:
          repository: eduard-cc/flair-api
          path: api

      - name: Copy API environment variables
        run: cp api/.env.test .env

      - name: Setup Docker E2E environment
        run: |
          cp web/docker-compose.e2e.yml docker-compose.e2e.yml
          docker compose -f docker-compose.e2e.yml up -d --build
          npx playwright install --with-deps

      - name: List Directory Contents
        run: ls -la
        working-directory: ./flair-web

      - name: Run E2E tests
        run: npm run test:e2e
        working-directory: ./flair-web

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
